# Generated by Django 4.0.2 on 2022-02-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_remove_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='password1',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='password2',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
