# Generated by Django 4.0.2 on 2022-02-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patient_password1_patient_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='password1',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='password2',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
